name: taxiflutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobx: ^2.0.7+4
  mobx_codegen: ^2.0.7
  build_runner: ^2.1.11
  provider: ^6.0.3
  flutter_mobx: ^2.0.6+1
  smooth_page_indicator: ^1.0.0+2
  mask_text_input_formatter: ^2.3.0
  modal_bottom_sheet: ^2.1.0
  flutter_datetime_picker: ^1.5.1
  flutter_rating_bar: ^4.0.1
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  pin_code_fields: ^7.4.0
  flutter_svg: ^1.1.1+1
  image_picker: ^0.8.5+3
  extended_image: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/welcome-screen/kaz.png
    - assets/svg/lock-screen.svg
    - assets/welcome-screen/first.png
    - assets/welcome-screen/second.png
    - assets/profile-photo.png
    - assets/svg/smart-phone-sms.svg


