name: taxizakaz
description: Такси приложения

publish_to: 'none'

version: 1.0.7+10

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobx: ^2.0.7+4
  mobx_codegen: ^2.0.7
  build_runner: ^2.1.11
  provider: ^6.0.3
  flutter_mobx: ^2.0.6+1
  smooth_page_indicator: ^1.0.0+2
  mask_text_input_formatter: ^2.3.0
  modal_bottom_sheet: ^3.0.0-pre
  flutter_datetime_picker: ^1.5.1
  flutter_rating_bar: ^4.0.1
  dio: ^5.0.0
  shared_preferences: ^2.0.15
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  pin_code_fields: ^7.4.0
  flutter_svg: ^2.0.1
  image_picker: ^0.8.5+3
  extended_image: ^8.1.1
  dotted_border: ^2.0.0+2
  tuple: ^2.0.0
  sticky_headers: ^0.3.0+2
  intl: ^0.18.0
  lottie: ^2.2.0
  fluttertoast: ^8.0.9
  firebase_messaging: ^14.2.4
  firebase_core: ^2.6.1
  in_app_notification: ^1.1.2
  url_launcher: ^6.1.6
  flutter_launcher_icons: ^0.11.0
  webview_flutter: ^4.0.1
  permission_handler: ^10.2.0
  flutter_datetime_picker_plus: ^2.0.1
  image_picker_for_web: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
flutter:
  uses-material-design: true

  assets:
    - assets/welcome-screen/kaz.png
    - assets/svg/lock-screen.svg
    - assets/welcome-screen/first.png
    - assets/welcome-screen/second.png
    - assets/taxi.png
    - assets/profile-photo.png
    - assets/lottie/success.json
    - assets/lottie/warning.json
    - assets/lottie/info-animation.json
    - assets/svg/smart-phone-sms.svg
    - assets/icons/car.png
    - assets/svg/order.svg
    - assets/lottie/active-taxi.json
    - assets/lottie/loading_car.json
    - assets/not-found.png


