// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjVlTAXrsxeelcJE0q7dTD_QMJfLP3cms',
    appId: '1:493521214399:web:2efa039aee8a993a9bdf0a',
    messagingSenderId: '493521214399',
    projectId: 'taxizakaz-d4d41',
    authDomain: 'taxizakaz-d4d41.firebaseapp.com',
    storageBucket: 'taxizakaz-d4d41.appspot.com',
    measurementId: 'G-RK29LZC3Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXAUGpfNFjqTkUIFRbbmqjPcUD8PDbrnk',
    appId: '1:493521214399:android:7a94b90b1d1dc3c69bdf0a',
    messagingSenderId: '493521214399',
    projectId: 'taxizakaz-d4d41',
    storageBucket: 'taxizakaz-d4d41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnhgBHMVOnhz-gery5fU6oUFqguVyzv0E',
    appId: '1:493521214399:ios:ccb42aa825fc4c5e9bdf0a',
    messagingSenderId: '493521214399',
    projectId: 'taxizakaz-d4d41',
    storageBucket: 'taxizakaz-d4d41.appspot.com',
    iosClientId: '493521214399-rilde5sdl88j0sltp8hckgcqgtsobtuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxizakaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnhgBHMVOnhz-gery5fU6oUFqguVyzv0E',
    appId: '1:493521214399:ios:ccb42aa825fc4c5e9bdf0a',
    messagingSenderId: '493521214399',
    projectId: 'taxizakaz-d4d41',
    storageBucket: 'taxizakaz-d4d41.appspot.com',
    iosClientId: '493521214399-rilde5sdl88j0sltp8hckgcqgtsobtuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxizakaz',
  );
}
